services:
  - type: web
    name: shatter-web
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: API_URL
        sync: false
      - key: NODE_ENV
        value: production
